AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first java lambda.

Resources:

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      Timeout: 30
      Handler: com.example.javalambda.HelloWorld::handleRequest
      Runtime: java8
      CodeUri: ./build/libs/JavaLambda-1.0-SNAPSHOT.jar